language: java

jdk:
  - oraclejdk8

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_db;' -U postgres

env:
  global:
    - JDBC_URL=jdbc:postgresql:travis_db
    - DB_USER=postgres
    - DB_PASSWORD=''